// <auto-generated />
using System;
using AspNetMvcBlogv2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetMvcBlogv2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230823114620_1001_ilk")]
    partial class _1001_ilk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetMvcBlogv2.Data.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("be845d0d-94d6-460c-b8df-933881b2c081"),
                            Email = "aras@gmail.com",
                            Name = "Aras",
                            Password = "123",
                            Surname = "Ment"
                        },
                        new
                        {
                            Id = new Guid("bafd5f4e-e54e-4c43-8b4b-670eeb721426"),
                            Email = "aksel@gmail.com",
                            Name = "Aksel",
                            Password = "321",
                            Surname = "Ment"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
