// <auto-generated />
using System;
using AspNetMvcBlogv2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetMvcBlogv2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230905094611_1002_ikinci")]
    partial class _1002_ikinci
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetMvcBlogv2.Data.Entity.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a8456cfb-c4eb-4f8f-9dc5-23e6cf5b30b8"),
                            Name = "Health and Fitness"
                        },
                        new
                        {
                            Id = new Guid("7b5f731a-7c6e-476c-bff8-34079fa706c4"),
                            Name = "Travel and Exploration"
                        },
                        new
                        {
                            Id = new Guid("2eb53053-e03c-45be-811a-0c103d235d1c"),
                            Name = "Personal Growth"
                        },
                        new
                        {
                            Id = new Guid("0245eafe-8a63-474d-94b3-9e19233344b0"),
                            Name = "Relationships"
                        },
                        new
                        {
                            Id = new Guid("140b30a6-119b-4b6a-ada9-8117209ffd9d"),
                            Name = "Creativity"
                        },
                        new
                        {
                            Id = new Guid("070ca9f3-5a93-404f-91dd-ff6abd4d0683"),
                            Name = "Sustainability"
                        });
                });

            modelBuilder.Entity("AspNetMvcBlogv2.Data.Entity.CategoryPost", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryId", "PostId");

                    b.HasIndex("PostId");

                    b.ToTable("CategoryPost");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("a8456cfb-c4eb-4f8f-9dc5-23e6cf5b30b8"),
                            PostId = new Guid("70f6ee74-0d24-44a0-8792-8cecbcac99df"),
                            Id = new Guid("b6f09a20-c223-4c98-9495-f61f1017ff68")
                        },
                        new
                        {
                            CategoryId = new Guid("7b5f731a-7c6e-476c-bff8-34079fa706c4"),
                            PostId = new Guid("0b0a00e8-814c-44de-a0c1-0dd5aa228043"),
                            Id = new Guid("9559b19d-7235-47e0-84e3-77627d857c75")
                        },
                        new
                        {
                            CategoryId = new Guid("2eb53053-e03c-45be-811a-0c103d235d1c"),
                            PostId = new Guid("278ea442-3103-400b-8f07-a2cd37aa5127"),
                            Id = new Guid("7dd7fbdb-69ad-4484-870d-747f7cf094db")
                        },
                        new
                        {
                            CategoryId = new Guid("140b30a6-119b-4b6a-ada9-8117209ffd9d"),
                            PostId = new Guid("4ae10166-39af-40fd-888a-f98af6a0491f"),
                            Id = new Guid("58d85fc6-f7eb-4ae0-9d80-70c5534e9ca6")
                        },
                        new
                        {
                            CategoryId = new Guid("0245eafe-8a63-474d-94b3-9e19233344b0"),
                            PostId = new Guid("4ae10166-39af-40fd-888a-f98af6a0491f"),
                            Id = new Guid("9fd16abc-bbd7-4e62-aa15-b9b609053048")
                        },
                        new
                        {
                            CategoryId = new Guid("140b30a6-119b-4b6a-ada9-8117209ffd9d"),
                            PostId = new Guid("567e6e99-bcab-4c9b-8ad2-e30be5613db4"),
                            Id = new Guid("c6a0c4da-9606-4610-9a65-106f3c5ab07d")
                        },
                        new
                        {
                            CategoryId = new Guid("070ca9f3-5a93-404f-91dd-ff6abd4d0683"),
                            PostId = new Guid("93068827-1f71-492e-a53e-e8e88c92fb04"),
                            Id = new Guid("5a0e0cf0-d560-4036-a679-1c434717e7d0")
                        });
                });

            modelBuilder.Entity("AspNetMvcBlogv2.Data.Entity.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Page");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6954a1f1-c350-4367-9600-e0dc9f282ab0"),
                            Content = "This is the about us page",
                            Title = "About Us"
                        },
                        new
                        {
                            Id = new Guid("5bbbc674-729c-462f-ad98-51919249b407"),
                            Content = "This is the contact page",
                            Title = "Contact"
                        });
                });

            modelBuilder.Entity("AspNetMvcBlogv2.Data.Entity.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Post");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70f6ee74-0d24-44a0-8792-8cecbcac99df"),
                            Content = "Maintaining a healthy lifestyle goes beyond hitting the gym; it's about making mindful choices every day. Whether it's choosing nutritious foods or finding joy in outdoor activities, taking small steps can lead to significant improvements in your overall well-being. Remember, your journey to better health is a marathon, not a sprint.",
                            PublishedAt = new DateTime(2023, 9, 5, 12, 46, 11, 835, DateTimeKind.Local).AddTicks(4764),
                            Title = "First Post",
                            UpdatedAt = new DateTime(2023, 9, 5, 12, 46, 11, 835, DateTimeKind.Local).AddTicks(4765)
                        },
                        new
                        {
                            Id = new Guid("0b0a00e8-814c-44de-a0c1-0dd5aa228043"),
                            Content = "Exploring new places broadens your horizons and enriches your life in ways you can't imagine. From the bustling streets of vibrant cities to the serene beauty of remote landscapes, every destination has a story to tell. So, pack your bags, embrace the adventure, and let the world be your teacher.",
                            PublishedAt = new DateTime(2023, 9, 5, 12, 46, 11, 835, DateTimeKind.Local).AddTicks(4766),
                            Title = "Second Post",
                            UpdatedAt = new DateTime(2023, 9, 5, 12, 46, 11, 835, DateTimeKind.Local).AddTicks(4767)
                        },
                        new
                        {
                            Id = new Guid("278ea442-3103-400b-8f07-a2cd37aa5127"),
                            Content = "Personal growth is a lifelong journey of self-discovery and self-improvement. It's about embracing change, learning from experiences, and continuously evolving into the best version of yourself. Remember, progress may be slow at times, but every step forward is a step closer to your goals.",
                            PublishedAt = new DateTime(2023, 9, 5, 12, 46, 11, 835, DateTimeKind.Local).AddTicks(4768),
                            Title = "Third Post",
                            UpdatedAt = new DateTime(2023, 9, 5, 12, 46, 11, 835, DateTimeKind.Local).AddTicks(4768)
                        },
                        new
                        {
                            Id = new Guid("4ae10166-39af-40fd-888a-f98af6a0491f"),
                            Content = "Strong and meaningful relationships are the cornerstone of a fulfilling life. Cultivate connections that are built on trust, communication, and mutual respect. These bonds will provide unwavering support and joy through life's ups and downs.",
                            PublishedAt = new DateTime(2023, 9, 5, 12, 46, 11, 835, DateTimeKind.Local).AddTicks(4770),
                            Title = "Forth Post",
                            UpdatedAt = new DateTime(2023, 9, 5, 12, 46, 11, 835, DateTimeKind.Local).AddTicks(4770)
                        },
                        new
                        {
                            Id = new Guid("567e6e99-bcab-4c9b-8ad2-e30be5613db4"),
                            Content = "Creativity knows no bounds, and it resides within each of us. Whether you express it through art, writing, music, or any other form, don't hesitate to let your imagination run wild. Your unique creative voice has the power to inspire, uplift, and change the world.",
                            PublishedAt = new DateTime(2023, 9, 5, 12, 46, 11, 835, DateTimeKind.Local).AddTicks(4771),
                            Title = "Fifth Post",
                            UpdatedAt = new DateTime(2023, 9, 5, 12, 46, 11, 835, DateTimeKind.Local).AddTicks(4772)
                        },
                        new
                        {
                            Id = new Guid("93068827-1f71-492e-a53e-e8e88c92fb04"),
                            Content = "The planet we call home needs our care and attention now more than ever. Embracing sustainable practices in our daily lives, from reducing waste to conserving energy, is not just a choice but a responsibility. Together, we can create a greener and healthier future for generations to come.",
                            PublishedAt = new DateTime(2023, 9, 5, 12, 46, 11, 835, DateTimeKind.Local).AddTicks(4773),
                            Title = "Sixst Post",
                            UpdatedAt = new DateTime(2023, 9, 5, 12, 46, 11, 835, DateTimeKind.Local).AddTicks(4773)
                        });
                });

            modelBuilder.Entity("AspNetMvcBlogv2.Data.Entity.PostComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("PostComment");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0bb2fce9-ea4c-4f8a-9a61-24620d993e9f"),
                            Content = "Your smile is absolutely radiant, lighting up the entire page!",
                            PostId = new Guid("70f6ee74-0d24-44a0-8792-8cecbcac99df")
                        },
                        new
                        {
                            Id = new Guid("b7fadc7f-21ea-499a-85ee-111ff3c35f29"),
                            Content = "What a charming face, your positivity is contagious!",
                            PostId = new Guid("0b0a00e8-814c-44de-a0c1-0dd5aa228043")
                        },
                        new
                        {
                            Id = new Guid("e9e137f2-0204-4d01-b382-d5d47da98949"),
                            Content = "You exude such warmth and kindness in every photo.",
                            PostId = new Guid("278ea442-3103-400b-8f07-a2cd37aa5127")
                        },
                        new
                        {
                            Id = new Guid("ee80e9af-ae59-4d1b-b09e-f863b688f542"),
                            Content = "A truly beautiful face that reflects an equally beautiful soul.",
                            PostId = new Guid("4ae10166-39af-40fd-888a-f98af6a0491f")
                        },
                        new
                        {
                            Id = new Guid("48239661-1de0-4b78-8a57-724a923d71cb"),
                            Content = "Your expressions are a delightful addition to this blog!",
                            PostId = new Guid("567e6e99-bcab-4c9b-8ad2-e30be5613db4")
                        },
                        new
                        {
                            Id = new Guid("f550f07a-7c85-430f-9691-3b0596a9ec0f"),
                            Content = "You've got that perfect combination of grace and charm.",
                            PostId = new Guid("93068827-1f71-492e-a53e-e8e88c92fb04")
                        },
                        new
                        {
                            Id = new Guid("62a24852-454c-40d2-857a-fbedfe5d34ef"),
                            Content = "Your face brightens up my day – thank you for sharing your joy!",
                            PostId = new Guid("0b0a00e8-814c-44de-a0c1-0dd5aa228043")
                        },
                        new
                        {
                            Id = new Guid("58764b8d-5654-447d-9d8f-c6a8bc10428f"),
                            Content = "Each picture tells a story of happiness and positivity.",
                            PostId = new Guid("278ea442-3103-400b-8f07-a2cd37aa5127")
                        },
                        new
                        {
                            Id = new Guid("1c5a89fd-ea17-4aad-90c2-90fd157a8bd3"),
                            Content = "Your face is a reflection of the sunshine in your heart.",
                            PostId = new Guid("4ae10166-39af-40fd-888a-f98af6a0491f")
                        },
                        new
                        {
                            Id = new Guid("6bddd77d-3b13-4088-84c7-828a850b74c8"),
                            Content = "Your presence adds a touch of elegance to this blog.",
                            PostId = new Guid("4ae10166-39af-40fd-888a-f98af6a0491f")
                        });
                });

            modelBuilder.Entity("AspNetMvcBlogv2.Data.Entity.PostImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("PostImage");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c01b423f-6205-4348-a3bd-f810c2bf8d8d"),
                            ImageUrl = "https://picsum.photos/id/10/150/200",
                            PostId = new Guid("70f6ee74-0d24-44a0-8792-8cecbcac99df")
                        },
                        new
                        {
                            Id = new Guid("ad5d0884-632d-4766-8ccc-d7161d75a33d"),
                            ImageUrl = "https://picsum.photos/id/11/150/200",
                            PostId = new Guid("0b0a00e8-814c-44de-a0c1-0dd5aa228043")
                        },
                        new
                        {
                            Id = new Guid("be3b2171-6def-4370-84c3-47608179761e"),
                            ImageUrl = "https://picsum.photos/id/12/150/200",
                            PostId = new Guid("278ea442-3103-400b-8f07-a2cd37aa5127")
                        },
                        new
                        {
                            Id = new Guid("debeb19e-3eaf-4408-b2d2-c31ce5106f86"),
                            ImageUrl = "https://picsum.photos/id/13/150/200",
                            PostId = new Guid("70f6ee74-0d24-44a0-8792-8cecbcac99df")
                        },
                        new
                        {
                            Id = new Guid("7fbd2309-2ec7-4779-91ef-a8551e66983d"),
                            ImageUrl = "https://picsum.photos/id/14/150/200",
                            PostId = new Guid("0b0a00e8-814c-44de-a0c1-0dd5aa228043")
                        },
                        new
                        {
                            Id = new Guid("132983cd-93c4-4c89-8117-cf11fd62714e"),
                            ImageUrl = "https://picsum.photos/id/15/150/200",
                            PostId = new Guid("278ea442-3103-400b-8f07-a2cd37aa5127")
                        });
                });

            modelBuilder.Entity("AspNetMvcBlogv2.Data.Entity.Setting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Setting");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dc982b2d-6fdf-4be7-897a-1cef03e17b9c"),
                            Name = "SiteName",
                            Value = "My Blog"
                        },
                        new
                        {
                            Id = new Guid("cb7825e0-6a91-46b7-b199-0919c676a6ce"),
                            Name = "MaxPostsPerPage",
                            Value = "10"
                        });
                });

            modelBuilder.Entity("AspNetMvcBlogv2.Data.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b8a1729-0321-4b82-963e-dceb77633d4e"),
                            Email = "test1@gmail.com",
                            Name = "user1",
                            Password = "123",
                            Surname = "TEST"
                        },
                        new
                        {
                            Id = new Guid("64a1f3c8-ae74-4b0e-814a-65cdb49b7c1f"),
                            Email = "test2@gmail.com",
                            Name = "user2",
                            Password = "123",
                            Surname = "TEST"
                        },
                        new
                        {
                            Id = new Guid("89385ee8-f953-4b2a-9f3c-4d4c81589a95"),
                            Email = "test3@gmail.com",
                            Name = "user3",
                            Password = "123",
                            Surname = "TEST"
                        },
                        new
                        {
                            Id = new Guid("75d4ad85-b9eb-484a-babc-debca518744b"),
                            Email = "test4@gmail.com",
                            Name = "user4",
                            Password = "123",
                            Surname = "TEST"
                        },
                        new
                        {
                            Id = new Guid("169d0b72-4f8f-4a00-9c08-a92b22073649"),
                            Email = "test5@gmail.com",
                            Name = "user5",
                            Password = "123",
                            Surname = "TEST"
                        },
                        new
                        {
                            Id = new Guid("9456a9bc-162e-4e87-bf98-13340f867bfb"),
                            Email = "test6@gmail.com",
                            Name = "user6",
                            Password = "123",
                            Surname = "TEST"
                        });
                });

            modelBuilder.Entity("AspNetMvcBlogv2.Data.Entity.CategoryPost", b =>
                {
                    b.HasOne("AspNetMvcBlogv2.Data.Entity.Category", "Category")
                        .WithMany("CategoryPosts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetMvcBlogv2.Data.Entity.Post", "Post")
                        .WithMany("CategoryPosts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("AspNetMvcBlogv2.Data.Entity.PostComment", b =>
                {
                    b.HasOne("AspNetMvcBlogv2.Data.Entity.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("AspNetMvcBlogv2.Data.Entity.PostImage", b =>
                {
                    b.HasOne("AspNetMvcBlogv2.Data.Entity.Post", "Post")
                        .WithMany("Images")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("AspNetMvcBlogv2.Data.Entity.Category", b =>
                {
                    b.Navigation("CategoryPosts");
                });

            modelBuilder.Entity("AspNetMvcBlogv2.Data.Entity.Post", b =>
                {
                    b.Navigation("CategoryPosts");

                    b.Navigation("Comments");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
